version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: USER_DATA
      DB_PASSWORD: PASSWORD_DATA
      DB_NAME: NAME_DATA
      PORT: 5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: NAME_DATA
      MYSQL_USER: USER_DATA
      MYSQL_PASSWORD: PASSWORD_DATA
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD_DATA
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
