name: Build and Push Docker Image MovtiGroup

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to HamDocker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.movtigroup.ir
          username: ${{ secrets.MOVTIGROUP_USERNAME }}
          password: ${{ secrets.MOVTIGROUP_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            registry.movtigroup.ir/tahavey18/flask_databese_manager_student:latest
