version: '3.8'

services:
  app:
    build: .
    expose:
      - "8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: USER_DATA
      DB_PASSWORD: PASSWORD_DATA
      DB_NAME: NAME_DATA
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: NAME_DATA
      MYSQL_USER: USER_DATA
      MYSQL_PASSWORD: PASSWORD_DATA
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD_DATA
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/app/logs
    depends_on:
      - app

volumes:
  db_data:
